#!/bin/bash
# 图谱增强功能测试脚本

echo "=== 🕸️  知识图谱增强功能测试 ==="
echo ""
echo "功能："
echo "  ✅ 图谱增强的意图识别"
echo "  ✅ 可视化管理界面"
echo "  ✅ 语义优化建议"
echo "  ✅ 图谱查询和编辑API"
echo ""
echo "📍 打开管理界面..."
echo ""

# 在浏览器中打开图谱管理界面
open /Users/wangzheng/Downloads/playDemo/AntigravityDemo/chatBI/frontend/graph-management.html

echo "✅ 管理界面已在浏览器中打开"
echo ""
echo "📊 功能说明："
echo ""
echo "1. 图谱统计"
echo "   - 节点总数（指标 + 领域）"
echo "   - 关系总数（同义词、相关、领域）"
echo "   - 实时数据更新"
echo ""
echo "2. 图谱可视化"
echo "   - 力导向图布局"
echo "   - 节点和关系连线"
echo "   - 点击查看详情"
echo ""
echo "3. 语义优化建议"
echo "   [HIGH]  缺少领域标注"
echo "   [MEDIUM] 缺少同义词链接"
echo "   [LOW]    缺少计算公式"
echo ""
echo "4. 搜索功能"
echo "   - 指标名称"
echo "   - 描述关键词"
echo "   - 同义词"
echo ""
echo "💡 核心优势："
echo "   - 图谱语义充分利用（5种关系类型）"
echo "   - 可视化管理界面"
echo "   - 智能优化建议"
echo "   - 完整的API体系"
echo ""
echo "🔗 API端点："
echo "   GET  /api/v1/graph/statistics"
echo "   GET  /api/v1/graph/nodes"
echo "   GET  /api/v1/graph/relations"
echo "   GET  /api/v1/graph/search"
echo "   GET  /api/v1/graph/suggestions"
echo "   POST /api/v1/graph/edit"
echo ""
